#!/usr/bin/zsh

if [ $($BSPCONFIG/helpers/check_installed.sh wmctrl) ] ; then
    exit 1
fi
if [ $($BSPCONFIG/helpers/check_installed.sh xdo) ] ; then
    exit 1
fi
wmctrl -l | awk '{print $1}' | while read -r wid ; do
    echo $wid $(ps -o command= -p $(xdo pid $wid) | awk '{print $1}')
done
