#! /bin/sh

bspc monitor -m west 1 2 3 4
bspc monitor -m east 1 2 3 4

# BSPWM config
bspc config border_width	4
bspc config window_gap		10
bspc config top_padding		37
bspc config bottom_padding	0
bspc config left_padding	0
bspc config right_padding	0

bspc config -m east top_padding 0

bspc config normal_border_color    \#222222
bspc config focused_border_color   \#7DFFFF
bspc config active_border_color    \#222222
bspc config presel_feedback_color  \#7DFFFF

bspc rule --add Wrapper\-\2\.\0 state=floating center=on rectangle=400x600+0+0 border=off

# Autostart
sxhkd -c ~/.config/bspwm/sxhkdrc &
picom --config ~/.config/bspwm/picom.conf --experimental-backends &

