#! /usr/bin/zsh

LOG_FILE="$HOME/.bspwm-singleton-log"

function startOrFocus() {
    echo "Request: $@" >> $LOG_FILE
    wids=(`$BSPCONFIG/helpers/get_window_cmds | grep $1 | awk '{print $1}' | tr '\n' ' '`)
    if [[ -z $wids ]] {
        launch_command=$1
        shift
        notify-send "Launching $launch_command"
        echo "Windows not found launching $launch_command $@">> $LOG_FILE
        $launch_command $@ &
        return
    }
    echo "Windows found: "$wids >> $LOG_FILE
    for wid in $wids; do
        echo "bspc node $wid --flag hidden=off --focus" >> $LOG_FILE
        bspc node $wid --flag hidden=off --focus
    done

}

if [[ $# == 0 ]] {
    echo "Usage: bspwm-singleton program "
    exit
}
startOrFocus $@
