#! /usr/bin/zsh

LOG_FILE="$HOME/.bspwm-singleton-log"

function startOrFocus() {
    if [[ $# != 1 ]] echo "Usage: bspwm-singleton cmd" && exit
        wids=(`$BSPCONFIG/helpers/get_window_cmds | grep $1 | awk '{print $1}' | tr '\n' ' '`)
    echo $wids >> $LOG_FILE
    if [[ -z $wids ]] {
        $1 &
        return
    }
    for wid in $wids; do
        echo "bspc node $wid --flag hidden=off --focus" >> $LOG_FILE
        bspc node $wid --flag hidden=off --focus
    done

}

if [[ $# == 0 ]] {
    echo "Usage: bspwm-singleton program "
    exit
}
startOrFocus $@
