#! /bin/sh

# bspc monitor DP-1 -d 1 2 3 4
# bspc monitor HDMI-1 -d 5 6 7 8
bspc monitor focused -d 1 2 3 4
bspc monitor east -d 5 6 7 8

# BSPWM config
bspc config border_width	4
bspc config window_gap		10
bspc config top_padding		37
bspc config bottom_padding	0
bspc config left_padding	0
bspc config right_padding	0

bspc config -m east top_padding 0

bspc config normal_border_color    \#222222
bspc config focused_border_color   \#7DFFFF
bspc config active_border_color    \#222222
bspc config presel_feedback_color  \#7DFFFF

bspc config external_rules_command "$HOME/.config/bspwm/external_rules"
# bspc rule --add Wrapper\-\2\.\0 state=floating center=on rectangle=400x600+0+0 border=off

# Set cursor to left_ptr
xsetroot -cursor_name left_ptr &

# Autostart
kill $(ps -C sxhkd,picom -o pid=)
sxhkd -c ~/.config/bspwm/sxhkdrc &
picom --config ~/.config/bspwm/picom.conf --experimental-backends &

# JVM hoolahoops
_JAVA_AWT_WM_NONREPARTENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'
wmname LG3D
