#! /bin/sh

export BSPCONFIG="$HOME/.config/bspwm"

bspc monitor primary --focus
if [ $(bspc query --monitors | wc -l ) = "3" ] ; then
    bspc monitor HDMI-0 -d V1 V2 V3 V4
    bspc monitor DP-2  -d 1 2 3 4 5 6
    bspc monitor DP-4 -d 7 8 9 0 Z M
else
    bspc monitor focused -d 1 2 3 4 5 Z M
    bspc monitor north -d 6 7 8 9 0
fi

# BSPWM config
bspc config border_width	4
bspc config window_gap		10
bspc config -m primary top_padding 37
bspc config -m east initial_polarity first_child
bspc config -m focused initial_polarity second_child
bspc config bottom_padding	0
bspc config left_padding	0
bspc config right_padding	0
bspc config remove_unplugged_monitors true

bspc config normal_border_color    \#222222
bspc config focused_border_color   \#7DFFFF
bspc config active_border_color    \#222222
bspc config presel_feedback_color  \#7DFFFF

bspc config pointer_modifier mod1

bspc config external_rules_command "$BSPCONFIG/external_rules"
# bspc rule --add Wrapper\-\2\.\0 state=floating center=on rectangle=400x600+0+0 border=off

# Autostart
kill -9 $(ps -C sxhkd,picom -o pid=)
sxhkd -c $BSPCONFIG/sxhkdrc &
picom --config $BSPCONFIG/picom.conf &

barrier &

# kill $(ps aux | grep 'bspwm-genmon-layout-refresher' | awk '{ print $2 }' | head --lines=-1)
# kill $(ps aux | grep 'bspwm-colorful-states' | awk '{ print $2 }' | head --lines=-1)
$BSPCONFIG/bspwm-genmon-layout-refresher &
$BSPCONFIG/bspwm-colorful-states &

bspc wm -o

# JVM hoolahoops
_JAVA_AWT_WM_NONREPARTENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'
wmname LG3D
