#! /bin/sh

wid=$1
class=$2
instance=$3
consequences=$4

echo $@ >> ~/.rules_cmd.log

case "$class" in
	'Wrapper-2.0')
        eval "$consequences"
        echo "monitor=west state=floating center=on follow=on rectangle=800x400+0+0"
        ;;
    'jetbrains-datagrip')
        eval "$consequences"
        echo "border=off"
        ;;
    'Xfce4-panel')
        eval "$consequences"
        echo "monitor=west state=floating follow=on"
        ;;
    'Xfce4-settings-manager') ;&
    'Blueman-manager') ;&
    'Blueberry.py')
        eval "$consequences"
        echo "monitor=west state=floating center=on follow=on"
        ;;
esac
